version: "3"

services:
  postfix:
    build: ./postfix
    hostname: mail.pedantry.org
    volumes:
      - mail:/var/mail
      - postfix_spool:/var/spool/postfix
      - spool_dovecot:/var/spool/postfix/dovecot:ro
      - spool_opendkim:/var/spool/postfix/opendkim:ro
      - spool_rspamd:/var/spool/postfix/rspamd:ro
      - ./etc/postfix:/etc/postfix:ro
      - /etc/letsencrypt/live/mail.pedantry.org:/etc/letsencrypt/live/mail.pedantry.org:ro
      - /etc/letsencrypt/archive/mail.pedantry.org:/etc/letsencrypt/archive/mail.pedantry.org:ro
    ports:
      - 25:25/tcp
      - 465:465/tcp
      - 587:587/tcp
  dovecot:
    build: ./dovecot
    hostname: mail.pedantry.org
    volumes:
      - mail:/var/mail
      - spool_dovecot:/var/spool/postfix/dovecot
      - ./etc/dovecot:/etc/dovecot:ro
      - /etc/letsencrypt/live/mail.pedantry.org:/etc/letsencrypt/live/mail.pedantry.org:ro
      - /etc/letsencrypt/archive/mail.pedantry.org:/etc/letsencrypt/archive/mail.pedantry.org:ro
    ports:
      - 110:110/tcp
      - 143:143/tcp
      - 993:993/tcp
      - 995:995/tcp
      - 4190:4190/tcp
  mail_mysql:
    build: ./mariadb
    hostname: mail.pedantry.org
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: dovecot
      MYSQL_PASSWORD: dovecot
      MYSQL_DATABASE: mail
    volumes:
      - mail_mysql:/var/lib/mysql
  opendkim:
    build: ./opendkim
    hostname: mail.pedantry.org
    volumes:
      - spool_opendkim:/var/spool/postfix/opendkim
      - ./etc/opendkim:/etc/opendkim:ro
  rspamd:
    build: ./rspamd
    hostname: mail.pedantry.org
    volumes:
      - spool_rspamd:/var/spool/postfix/rspamd
      - ./etc/rspamd/local.d:/etc/rspamd/local.d:ro
      - ./etc/rspamd/override.d:/etc/rspamd/override.d:ro
    ports:
      - 11333:11333/tcp
      - 127.0.0.1:11334:11334/tcp
  rspamd_redis:
    image: redis:6.2
    volumes:
      - rspamd_redis:/data
  roundcube:
    build: ./roundcube
    hostname: mail.pedantry.org
    volumes:
      - roundcube_enigma:/var/lib/enigma
      - ./etc/roundcube:/var/www/html/config:ro
    ports:
      - 8080:80/tcp
  roundcube_mysql:
    image: mariadb:focal
    hostname: mail.pedantry.org
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcube
      MYSQL_DATABASE: roundcube
    volumes:
      - roundcube_mysql:/var/lib/mysql

volumes:
  mail:
  postfix_spool:
  mail_mysql:
  rspamd_redis:
  roundcube_enigma:
  roundcube_mysql:
  spool_dovecot:
  spool_opendkim:
  spool_rspamd:
