version: "3"

services:
  postfix:
    build:
      context: .
      dockerfile: ./postfix.Dockerfile
    hostname: mail.ngai.me
    restart: always
    volumes:
      - mail:/var/mail
      - postfix_spool:/var/spool/postfix
      - spool_dovecot:/var/spool/postfix/dovecot:ro
      - spool_opendkim:/var/spool/postfix/opendkim:ro
      - spool_opendmarc:/var/spool/postfix/opendmarc:ro
      - ./etc/postfix/sasl_passwd:/etc/postfix/sasl_passwd:ro
      - /etc/letsencrypt/live/mail.ngai.me:/etc/letsencrypt/live/mail.ngai.me:ro
      - /etc/letsencrypt/archive/mail.ngai.me:/etc/letsencrypt/archive/mail.ngai.me:ro
    ports:
      - 25:25/tcp
      - 465:465/tcp
      - 587:587/tcp
    depends_on:
      - dovecot
      - opendkim
      - opendmarc
  dovecot:
    build:
      context: .
      dockerfile: ./dovecot.Dockerfile
    hostname: mail.ngai.me
    restart: always
    volumes:
      - mail:/var/mail
      - spool_dovecot:/var/spool/postfix/dovecot
      - /etc/letsencrypt/live/mail.ngai.me:/etc/letsencrypt/live/mail.ngai.me:ro
      - /etc/letsencrypt/archive/mail.ngai.me:/etc/letsencrypt/archive/mail.ngai.me:ro
    ports:
      - 110:110/tcp
      - 143:143/tcp
      - 993:993/tcp
      - 995:995/tcp
      - 4190:4190/tcp
    depends_on:
      - mail_mysql
  mail_mysql:
    build:
      context: .
      dockerfile: ./mariadb.Dockerfile
    hostname: mail.ngai.me
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: dovecot
      MYSQL_PASSWORD: dovecot
      MYSQL_DATABASE: mail
    volumes:
      - mail_mysql:/var/lib/mysql
  opendkim:
    build:
      context: .
      dockerfile: ./opendkim.Dockerfile
    hostname: mail.ngai.me
    restart: always
    volumes:
      - spool_opendkim:/var/spool/postfix/opendkim
      - ./etc/opendkim/keys:/etc/opendkim/keys:ro
  opendmarc:
    build:
      context: .
      dockerfile: ./opendmarc.Dockerfile
    hostname: mail.ngai.me
    restart: always
    volumes:
      - spool_opendmarc:/var/spool/postfix/opendmarc
  roundcube:
    build:
      context: .
      dockerfile: ./roundcube.Dockerfile
    hostname: mail.ngai.me
    restart: always
    volumes:
      - roundcube_enigma:/var/lib/enigma
    ports:
      - 8080:80/tcp
    depends_on:
      - roundcube_mysql
  roundcube_mysql:
    image: mariadb:focal
    hostname: mail.ngai.me
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcube
      MYSQL_DATABASE: roundcube
    volumes:
      - roundcube_mysql:/var/lib/mysql

volumes:
  mail:
  postfix_spool:
  mail_mysql:
  roundcube_enigma:
  roundcube_mysql:
  spool_dovecot:
  spool_opendkim:
  spool_opendmarc:
