version: "3"

services:
  postfix:
    build: ./postfix
    hostname: mail.pedantry.org
    volumes:
      - mail:/var/mail
      - postfix_spool:/var/spool/postfix
      - spool_dovecot:/var/spool/postfix/dovecot:ro
      - spool_opendkim:/var/spool/postfix/opendkim:ro
      - spool_opendmarc:/var/spool/postfix/opendmarc:ro
      - ./etc/postfix:/etc/postfix:ro
      - /etc/letsencrypt/live/mail.pedantry.org:/etc/letsencrypt/live/mail.pedantry.org:ro
      - /etc/letsencrypt/archive/mail.pedantry.org:/etc/letsencrypt/archive/mail.pedantry.org:ro
    ports:
      - 25:25/tcp
      - 465:465/tcp
      - 587:587/tcp
  dovecot:
    build: ./dovecot
    hostname: mail.pedantry.org
    volumes:
      - mail:/var/mail
      - spool_dovecot:/var/spool/postfix/dovecot
      - ./etc/dovecot:/etc/dovecot:ro
      - /etc/letsencrypt/live/mail.pedantry.org:/etc/letsencrypt/live/mail.pedantry.org:ro
      - /etc/letsencrypt/archive/mail.pedantry.org:/etc/letsencrypt/archive/mail.pedantry.org:ro
    ports:
      - 110:110/tcp
      - 143:143/tcp
      - 993:993/tcp
      - 995:995/tcp
      - 4190:4190/tcp
  mysql:
    build: ./mariadb
    hostname: mail.pedantry.org
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: dovecot
      MYSQL_PASSWORD: dovecot
      MYSQL_DATABASE: mail
    volumes:
      - mysql:/var/lib/mysql
  opendkim:
    build: ./opendkim
    hostname: mail.pedantry.org
    volumes:
      - spool_opendkim:/var/spool/postfix/opendkim
      - ./etc/opendkim:/etc/opendkim:ro
  opendmarc:
    build: ./opendmarc
    hostname: mail.pedantry.org
    volumes:
      - spool_opendmarc:/var/spool/postfix/opendmarc
      - ./etc/opendmarc:/etc/opendmarc:ro

volumes:
  mail:
  postfix_spool:
  mysql:
  spool_dovecot:
  spool_opendkim:
  spool_opendmarc:
